"""
MNIST Grid World — Phase 1 demonstration environment.

Each cell of a 2-D grid is labelled with a digit class (0..9). Visiting the
cell returns a *random MNIST image* of that class. Two cells with the same
digit therefore produce visually-similar but never-identical observations,
which is exactly the kind of perceptual aliasing a CSCG/clone-HMM is designed
to disambiguate using action context.

Action space: 4 actions (up/down/left/right). Off-grid moves stick (the
agent stays in place).

Trajectories are generated by uniform random walks unless a custom action
policy is supplied.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, List, Optional, Sequence, Tuple

import numpy as np
import tensorflow as tf

ACTION_DELTAS: Tuple[Tuple[int, int], ...] = (
    (-1, 0),  # 0 up
    (1, 0),   # 1 down
    (0, -1),  # 2 left
    (0, 1),   # 3 right
)


def load_mnist(
    flatten: bool = False, normalize: bool = True
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return ``(x_train, y_train, x_test, y_test)`` shaped ``[N, 28, 28, 1]``."""
    (x_tr, y_tr), (x_te, y_te) = tf.keras.datasets.mnist.load_data()
    x_tr = x_tr.astype(np.float32)
    x_te = x_te.astype(np.float32)
    if normalize:
        x_tr /= 255.0
        x_te /= 255.0
    if not flatten:
        x_tr = x_tr[..., None]
        x_te = x_te[..., None]
    return x_tr, y_tr.astype(np.int64), x_te, y_te.astype(np.int64)


@dataclass
class _DigitBank:
    """Indexes MNIST images by digit class so cell visits can sample fast."""

    images: np.ndarray  # [N, 28, 28, 1]
    by_class: List[np.ndarray]  # by_class[d] = indices into images

    @classmethod
    def from_dataset(cls, images: np.ndarray, labels: np.ndarray) -> "_DigitBank":
        return cls(
            images=images,
            by_class=[np.where(labels == d)[0] for d in range(10)],
        )

    def sample(self, digit: int, rng: np.random.Generator) -> np.ndarray:
        idx = self.by_class[digit]
        return self.images[idx[rng.integers(0, idx.size)]]


class MNISTGridWorld:
    """A 2-D grid where each cell yields random MNIST images of a digit class.

    Parameters
    ----------
    digit_grid
        ``(H, W)`` int array of digits in ``[0, 9]``. Cells with value ``-1``
        are walls (inaccessible).
    images, labels
        MNIST training set (or any subset). Used as the bank of perceptual
        observations.
    seed
        Optional RNG seed.
    """

    def __init__(
        self,
        digit_grid: np.ndarray,
        images: np.ndarray,
        labels: np.ndarray,
        seed: Optional[int] = None,
    ) -> None:
        digit_grid = np.asarray(digit_grid, dtype=np.int64)
        if digit_grid.ndim != 2:
            raise ValueError("digit_grid must be 2-D")
        if (digit_grid != -1).sum() == 0:
            raise ValueError("digit_grid has no walkable cells")
        for v in np.unique(digit_grid):
            if v != -1 and not 0 <= v <= 9:
                raise ValueError(f"digit values must be in [0,9] or -1, got {v}")

        self.digit_grid = digit_grid
        self.height, self.width = digit_grid.shape
        self.bank = _DigitBank.from_dataset(images, labels)
        self.rng = np.random.default_rng(seed)
        self.image_shape: Tuple[int, int, int] = images.shape[1:]
        self.num_actions: int = 4

    # ---- pure environment dynamics ----
    def is_walkable(self, r: int, c: int) -> bool:
        return (
            0 <= r < self.height
            and 0 <= c < self.width
            and int(self.digit_grid[r, c]) != -1
        )

    def step(self, r: int, c: int, action: int) -> Tuple[int, int]:
        dr, dc = ACTION_DELTAS[int(action)]
        nr, nc = r + dr, c + dc
        if not self.is_walkable(nr, nc):
            return r, c
        return nr, nc

    def random_walkable_cell(self) -> Tuple[int, int]:
        walkable = np.argwhere(self.digit_grid != -1)
        idx = self.rng.integers(0, walkable.shape[0])
        r, c = walkable[idx]
        return int(r), int(c)

    def observe(self, r: int, c: int) -> np.ndarray:
        digit = int(self.digit_grid[r, c])
        return self.bank.sample(digit, self.rng)

    # ---- trajectory generation ----
    def rollout(
        self,
        steps: int,
        start: Optional[Tuple[int, int]] = None,
        policy: Optional[Callable[[int, int, np.random.Generator], int]] = None,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
        """Generate one episode of length ``steps``.

        Returns
        -------
        images : ``[T, H, W, C]`` float32
        actions : ``[T]`` int32 (action *taken at* step t, transitioning to t+1)
        positions : ``[T, 2]`` int32 (r, c)
        cell_digits : ``[T]`` int32 (ground-truth digit per step)
        """
        if start is None:
            r, c = self.random_walkable_cell()
        else:
            r, c = int(start[0]), int(start[1])
            if not self.is_walkable(r, c):
                raise ValueError(f"start ({r}, {c}) is not walkable")

        images = np.empty((steps,) + self.image_shape, dtype=np.float32)
        actions = np.empty((steps,), dtype=np.int32)
        positions = np.empty((steps, 2), dtype=np.int32)
        cell_digits = np.empty((steps,), dtype=np.int32)

        for t in range(steps):
            images[t] = self.observe(r, c)
            positions[t] = (r, c)
            cell_digits[t] = int(self.digit_grid[r, c])
            if policy is None:
                a = int(self.rng.integers(0, 4))
            else:
                a = int(policy(r, c, self.rng))
            actions[t] = a
            r, c = self.step(r, c, a)

        return images, actions, positions, cell_digits


def rollout_episodes(
    env: MNISTGridWorld,
    n_episodes: int,
    steps_per_episode: int,
    policy: Optional[Callable[[int, int, np.random.Generator], int]] = None,
) -> Tuple[List[np.ndarray], List[np.ndarray], List[np.ndarray], List[np.ndarray]]:
    """Roll out ``n_episodes`` random walks. Returns parallel lists.

    Each list element corresponds to one episode:
    ``image_seqs[i]`` is shape ``[T, H, W, C]``, etc.
    """
    img_eps: List[np.ndarray] = []
    act_eps: List[np.ndarray] = []
    pos_eps: List[np.ndarray] = []
    digit_eps: List[np.ndarray] = []
    for _ in range(n_episodes):
        imgs, acts, pos, digits = env.rollout(steps_per_episode, policy=policy)
        img_eps.append(imgs)
        act_eps.append(acts)
        pos_eps.append(pos)
        digit_eps.append(digits)
    return img_eps, act_eps, pos_eps, digit_eps


# ----------------------------------------------------------------------
# Example digit grids for quick experimentation
# ----------------------------------------------------------------------

def example_grid_unique() -> np.ndarray:
    """A 3x3 grid where every cell has a distinct digit (no aliasing)."""
    return np.array(
        [
            [0, 1, 2],
            [3, 4, 5],
            [6, 7, 8],
        ],
        dtype=np.int64,
    )


def example_grid_aliased() -> np.ndarray:
    """A 4x4 grid with strong perceptual aliasing.

    Multiple cells share each digit class, so the HMM must use action context
    to disambiguate them via clone states.
    """
    return np.array(
        [
            [0, 1, 0, 1],
            [2, 3, 2, 3],
            [0, 1, 0, 1],
            [2, 3, 2, 3],
        ],
        dtype=np.int64,
    )


def example_grid_corridors() -> np.ndarray:
    """A 5x5 grid with walls (-1) and repeated digits in corridors."""
    return np.array(
        [
            [0, 1, 1, 1, 2],
            [3, -1, 0, -1, 4],
            [3, -1, 0, -1, 4],
            [3, -1, 0, -1, 4],
            [6, 6, 1, 1, 5],
        ],
        dtype=np.int64,
    )

def example_grid_notebook_room() -> np.ndarray:
    """The original 6x6 ``observation_indices`` grid from the notebook.

    Heavy aliasing on the central "20" plateau plus several edge digits.
    Useful for reproducing the rectangular-room transition graph in the
    original gradient-CSCG demo.
    """
    return np.array(
        [
            [1, 1, 3, 2, 2, 2],
            [1, 1, 3, 5, 3, 2],
            [8, 7, 7, 5, 4, 6],
            [8, 9, 4, 0, 0, 7],
            [9, 9, 9, 0, 0, 7],
            [9, 4, 4, 5, 5, 7],
        ],
        dtype=np.int64,
    )

def example_grid_empty_notebook_room() -> np.ndarray:
    """The original 6x6 ``observation_indices`` grid from the notebook.

    Heavy aliasing on the central "20" plateau plus several edge digits.
    Useful for reproducing the rectangular-room transition graph in the
    original gradient-CSCG demo.
    """
    return np.array(
        [
            [1, 1, 3, 2, 2, 2],
            [1, 0, 0, 0, 0, 2],
            [8, 0, 0, 0, 0, 6],
            [8, 0, 0, 0, 0, 7],
            [9, 0, 0, 0, 0, 7],
            [9, 4, 4, 5, 5, 7],
        ],
        dtype=np.int64,
    )


def example_grid_two_rooms() -> np.ndarray:
    """Two offset, interconnected rooms with repeated MNIST observations.

    The layout mirrors the two-room schematic: two 8x6 rooms are offset so the
    first room's lower-right 3x3 patch is the same physical/observational
    pattern as the second room's upper-left 3x3 patch. Cells outside the rooms
    are walls. Repeated digits create aliased observations across and within
    rooms, while the shared patch is a true connection between them.
    """
    grid = -np.ones((13, 9), dtype=np.int64)

    first_room = np.array(
        [
            [8, 4, 0, 1, 2, 3],
            [9, 4, 5, 6, 0, 7],
            [9, 2, 8, 6, 7, 4],
            [4, 0, 8, 9, 3, 7],
            [4, 6, 9, 1, 2, 0],
            [9, 8, 7, 1, 5, 6],
            [0, 0, 9, 3, 5, 6],
            [4, 7, 3, 0, 8, 7],
        ],
        dtype=np.int64,
    )
    second_room = np.array(
        [
            [1, 5, 6, 4, 6, 0],
            [3, 5, 6, 7, 9, 2],
            [0, 8, 7, 4, 3, 1],
            [9, 2, 4, 7, 6, 8],
            [1, 0, 5, 3, 9, 8],
            [8, 7, 3, 6, 4, 2],
            [5, 9, 1, 0, 8, 4],
            [6, 2, 7, 5, 3, 0],
        ],
        dtype=np.int64,
    )

    # First room: rows 0..7, cols 0..5.
    # Second room: rows 5..12, cols 3..8.
    # The 3x3 overlap at first[5:8, 3:6] == second[0:3, 0:3].
    grid[0:8, 0:6] = first_room
    grid[5:13, 3:9] = second_room
    return grid
